export const GET_USER_REQUESTED = 'GET_USER_REQUESTED';
export const GET_USERS_SUCCEEDED = 'GET_USERS_SUCCEEDED';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';
export const SESSION_EXPIRE_REQUESTED = 'SESSION_EXPIRE_REQUESTED';
export const SESSION_EXPIRED = 'SESSION_EXPIRED';
