const actionTypes = {
    GET_USERS: 'GET_USERS',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    STOP_USERS_LOADING: 'STOP_USERS_LOADING',
    UPDATE_NET_INFO: 'UPDATE_NET_INFO',
};

export { actionTypes };
